#spring配置
spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/wxshop?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
      username: root
      password: 1213
      initial-size: 5
      max-active: 100
      max-wait: 50000
      min-idle: 1
  http:
    encoding:
      charset: UTF-8
  resources:
    static-locations: classpath:/static

  thymeleaf:
    cache: false
  mvc:
    view:
      suffix: .html
      prefix: /templates/
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

#Mybatis配置
mybatis:
  type-aliases-package: com.huang.pojo
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helper-dialect: mysql
server:
  address: 0.0.0.0